## Load API Key

In [1]:
import os
from dotenv import load_dotenv

In [3]:
load_dotenv()

True

In [4]:
key = os.getenv("tmdb_API_key") # should be changed to whatever the key is
print("API key loaded:", key is not None) # check key was loaded correctly

API key loaded: True

## Fetch All Movies of Interest

In [7]:
import requests
import json
import time

In [8]:
# use pagination to request movie lists in any endpoint
def fetch_movies(category, extra_params, pages = 5, delay = 0.5, api_key = key, verbose = True):
    
    base_url = "https://api.themoviedb.org/3/discover/movie" # use discover endpoint to get details of movies
    all_movies= [] # initialize list to store movies
    
    print(f"Fetching {category} movies:")


    for page in range(1, pages + 1):
        
        # define parameters for requests.get() function
        params = {
            'api_key': api_key,
            'page': page,
            **extra_params
        }

        try: # get results from page and save results in all_movies
            response = requests.get(base_url, params = params) # get results of page
            response.raise_for_status() # throw status
            data = response.json() # save data as json

            if 'results' in data:
                all_movies.extend(data['results']) # add elements (append) to the end of the movies list
                if verbose == True:
                    print(f" Page {page}: {len(data['results'])} movies") # print progress
            else:
                print(f"No Results on Page {page}")

        except requests.exceptions.RequestException as e: # stop code from running
            print(f"Error on Page {page}: {e}")
            break
        time.sleep(delay) # ensure api limit

    print(f"Success! Total {category}: {len(all_movies)} movies")

    return all_movies

In [11]:
# define ways to search discover endpoint
categories = {

    # include only top rated movies, defined by top 100 movies with at least 1000 votes
    "Top Rated": {
        "extra_params": {
            "sort_by": "vote_average.desc",
            "vote_count.gte": 1000
        }
    },

    # include medium rated movies, defined by movies with an average rating of 4.5-7.5 and at least 100 votes
    "Medium Rated": {
        "extra_params": {
            "sort_by": "vote_average.desc",
            "vote_average.gte": 4.5,
            "vote_average.lte": 7.5,
            "vote_count.gte": 100
        }
    },

    # include bottom rated movies, defined by movies with an average rating of below 4.5 and at least 100 votes
    "Bottom Rated": {
        "extra_params": {
            "sort_by": "vote_average.asc",
            "vote_average.lte": 4.5,
            "vote_count.gte": 100
        }
    },

    # include most popular movies
    "Most Popular Rated": {
        "extra_params": {
            "sort_by": "popularity.desc",
            "vote_count.gte": 100
        }
    },

    # include least popular movies
    "Least Popular Rated": {
        "extra_params": {
            "sort_by": "popularity.asc",
            "vote_count.gte": 100
        }
    }
}

In [13]:
# define function to go through categories and return movie data
def fetch_all_movies(categories, pages_per_category = 5, delay = 0.5):
    full_dataset = [] # initialize dataset to store all movies

    for name, cfg in categories.items():
        # call helper function to grab movies
        movies = fetch_movies(
            category = name,
            extra_params = cfg['extra_params'],
            pages = pages_per_category,
            delay = delay
        )
        
        full_dataset.extend(movies) # add elements (append) to the end of the movies list

    print(f"Total Movies Across All Categories: {len(full_dataset)}")

    return full_dataset

In [15]:
# uncomment when you want to request data
# all_movies = fetch_all_movies(categories, pages_per_category = 10)

Fetching Top Rated movies:
 Page 1: 20 movies
 Page 2: 20 movies
 Page 3: 20 movies
 Page 4: 20 movies
 Page 5: 20 movies
 Page 6: 20 movies
 Page 7: 20 movies
 Page 8: 20 movies
 Page 9: 20 movies
 Page 10: 20 movies
Success! Total Top Rated: 200 movies
Fetching Medium Rated movies:
 Page 1: 20 movies
 Page 2: 20 movies
 Page 3: 20 movies
 Page 4: 20 movies
 Page 5: 20 movies
 Page 6: 20 movies
 Page 7: 20 movies
 Page 8: 20 movies
 Page 9: 20 movies
 Page 10: 20 movies
Success! Total Medium Rated: 200 movies
Fetching Bottom Rated movies:
 Page 1: 20 movies
 Page 2: 20 movies
 Page 3: 20 movies
 Page 4: 20 movies
 Page 5: 20 movies
 Page 6: 20 movies
 Page 7: 20 movies
 Page 8: 20 movies
 Page 9: 20 movies
 Page 10: 20 movies
Success! Total Bottom Rated: 200 movies
Fetching Most Popular Rated movies:
 Page 1: 20 movies
 Page 2: 20 movies
 Page 3: 20 movies
 Page 4: 20 movies
 Page 5: 20 movies
 Page 6: 20 movies
 Page 7: 20 movies
 Page 8: 20 movies
 Page 9: 20 movies
 Page 10: 20 movies
Success! Total Most Popular Rated: 200 movies
Fetching Least Popular Rated movies:
 Page 1: 20 movies
 Page 2: 20 movies
 Page 3: 20 movies
 Page 4: 20 movies
 Page 5: 20 movies
 Page 6: 20 movies
 Page 7: 20 movies
 Page 8: 20 movies
 Page 9: 20 movies
 Page 10: 20 movies
Success! Total Least Popular Rated: 200 movies
Total Movies Across All Categories: 1000

## Add More Data to Each Movie

In [17]:
def fetch_movie_details(movie_id, api_key = key):
    base_url = f"https://api.themoviedb.org/3/movie/{movie_id}"
    params = {'api_key': api_key}

    try:
        response = requests.get(base_url, params = params)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"Unable to Fetch Details for Movie ID {movie_id}: {e}")
        return None

In [19]:
def fetch_all_movie_details(movie_list, delay = 0.5, max_movies = None, api_key = key, verbose = True):
    movies_detailed = []
    for i, movie in enumerate(movie_list):
        if max_movies and i >= max_movies:
            break

        movie_id = movie.get('id')
        if movie_id:
            details = fetch_movie_details(movie_id, api_key)
            if details:
                movies_detailed.append(details)
                if verbose == True:
                    print(f"{i + 1}: Got Details For Movie Titled: {details.get('title')}")
            time.sleep(delay)

    return movies_detailed

In [89]:
# uncomment when you want to request data
detailed_data = fetch_all_movie_details(all_movies, delay = 0.5)

1: Got Details For Movie Titled: The Shawshank Redemption
2: Got Details For Movie Titled: The Godfather
3: Got Details For Movie Titled: The Godfather Part II
4: Got Details For Movie Titled: Schindler's List
5: Got Details For Movie Titled: 12 Angry Men
6: Got Details For Movie Titled: Spirited Away
7: Got Details For Movie Titled: The Dark Knight
8: Got Details For Movie Titled: Dilwale Dulhania Le Jayenge
9: Got Details For Movie Titled: The Green Mile
10: Got Details For Movie Titled: Parasite
11: Got Details For Movie Titled: Pulp Fiction
12: Got Details For Movie Titled: Your Name.
13: Got Details For Movie Titled: The Lord of the Rings: The Return of the King
14: Got Details For Movie Titled: Forrest Gump
15: Got Details For Movie Titled: The Good, the Bad and the Ugly
16: Got Details For Movie Titled: Seven Samurai
17: Got Details For Movie Titled: GoodFellas
18: Got Details For Movie Titled: Interstellar
19: Got Details For Movie Titled: Grave of the Fireflies
20: Got Details For Movie Titled: Life Is Beautiful
21: Got Details For Movie Titled: Fight Club
22: Got Details For Movie Titled: Cinema Paradiso
23: Got Details For Movie Titled: City of God
24: Got Details For Movie Titled: A Dog's Will
25: Got Details For Movie Titled: Psycho
26: Got Details For Movie Titled: The Lord of the Rings: The Fellowship of the Ring
27: Got Details For Movie Titled: Harakiri
28: Got Details For Movie Titled: One Flew Over the Cuckoo's Nest
29: Got Details For Movie Titled: Gabriel's Inferno
30: Got Details For Movie Titled: Once Upon a Time in America
31: Got Details For Movie Titled: The Lord of the Rings: The Two Towers
32: Got Details For Movie Titled: Spider-Man: Into the Spider-Verse
33: Got Details For Movie Titled: Howl's Moving Castle
34: Got Details For Movie Titled: The Empire Strikes Back
35: Got Details For Movie Titled: A Silent Voice: The Movie
36: Got Details For Movie Titled: Gabriel's Inferno: Part II
37: Got Details For Movie Titled: The Pianist
38: Got Details For Movie Titled: Gabriel's Inferno: Part III
39: Got Details For Movie Titled: Whiplash
40: Got Details For Movie Titled: Se7en
41: Got Details For Movie Titled: Inception
42: Got Details For Movie Titled: Rear Window
43: Got Details For Movie Titled: The Silence of the Lambs
44: Got Details For Movie Titled: Spider-Man: Across the Spider-Verse
45: Got Details For Movie Titled: American History X
46: Got Details For Movie Titled: Princess Mononoke
47: Got Details For Movie Titled: The Wild Robot
48: Got Details For Movie Titled: Back to the Future
49: Got Details For Movie Titled: Ikiru
50: Got Details For Movie Titled: Perfect Blue
51: Got Details For Movie Titled: Dead Poets Society
52: Got Details For Movie Titled: Léon: The Professional
53: Got Details For Movie Titled: The Great Dictator
54: Got Details For Movie Titled: Sunset Boulevard
55: Got Details For Movie Titled: Neon Genesis Evangelion: The End of Evangelion
56: Got Details For Movie Titled: Modern Times
57: Got Details For Movie Titled: Once Upon a Time in the West
58: Got Details For Movie Titled: Hotarubi no Mori e
59: Got Details For Movie Titled: It's a Wonderful Life
60: Got Details For Movie Titled: The Intouchables
61: Got Details For Movie Titled: Apocalypse Now
62: Got Details For Movie Titled: City Lights
63: Got Details For Movie Titled: Miracle in Cell No. 7
64: Got Details For Movie Titled: The Lion King
65: Got Details For Movie Titled: Paths of Glory
66: Got Details For Movie Titled: The Legend of 1900
67: Got Details For Movie Titled: Oldboy
68: Got Details For Movie Titled: Clouds
69: Got Details For Movie Titled: One Direction: This Is Us
70: Got Details For Movie Titled: Life in a Year
71: Got Details For Movie Titled: I Want to Eat Your Pancreas
72: Got Details For Movie Titled: Five Feet Apart
73: Got Details For Movie Titled: Klaus
74: Got Details For Movie Titled: Avengers: Endgame
75: Got Details For Movie Titled: Avengers: Infinity War
76: Got Details For Movie Titled: Come and See
77: Got Details For Movie Titled: Green Book
78: Got Details For Movie Titled: Mommy
79: Got Details For Movie Titled: The Matrix
80: Got Details For Movie Titled: Justice League Dark: Apokolips War
81: Got Details For Movie Titled: Wolf Children
82: Got Details For Movie Titled: Gladiator
83: Got Details For Movie Titled: Saving Private Ryan
84: Got Details For Movie Titled: Wolfwalkers
85: Got Details For Movie Titled: Puss in Boots: The Last Wish
86: Got Details For Movie Titled: Witness for the Prosecution
87: Got Details For Movie Titled: Inglourious Basterds
88: Got Details For Movie Titled: Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train
89: Got Details For Movie Titled: The Shining
90: Got Details For Movie Titled: The Help
91: Got Details For Movie Titled: Coco
92: Got Details For Movie Titled: The Handmaiden
93: Got Details For Movie Titled: Star Wars
94: Got Details For Movie Titled: The Prestige
95: Got Details For Movie Titled: The Apartment
96: Got Details For Movie Titled: Shutter Island
97: Got Details For Movie Titled: The Art of Racing in the Rain
98: Got Details For Movie Titled: Flow
99: Got Details For Movie Titled: Hacksaw Ridge
100: Got Details For Movie Titled: A Clockwork Orange
101: Got Details For Movie Titled: The Seventh Seal
102: Got Details For Movie Titled: Django Unchained
103: Got Details For Movie Titled: Bicycle Thieves
104: Got Details For Movie Titled: Tokyo Story
105: Got Details For Movie Titled: Top Gun: Maverick
106: Got Details For Movie Titled: Memento
107: Got Details For Movie Titled: The Usual Suspects
108: Got Details For Movie Titled: Alien
109: Got Details For Movie Titled: Vertigo
110: Got Details For Movie Titled: Scarface
111: Got Details For Movie Titled: The Departed
112: Got Details For Movie Titled: Casablanca
113: Got Details For Movie Titled: My Hero Academia: Heroes Rising
114: Got Details For Movie Titled: Persona
115: Got Details For Movie Titled: Good Will Hunting
116: Got Details For Movie Titled: Hamilton
117: Got Details For Movie Titled: The Kid
118: Got Details For Movie Titled: Dune: Part Two
119: Got Details For Movie Titled: Capernaum
120: Got Details For Movie Titled: Piper
121: Got Details For Movie Titled: The Truman Show
122: Got Details For Movie Titled: Singin' in the Rain
123: Got Details For Movie Titled: Togo
124: Got Details For Movie Titled: Joker
125: Got Details For Movie Titled: 8½
126: Got Details For Movie Titled: Taxi Driver
127: Got Details For Movie Titled: Bound by Honor
128: Got Details For Movie Titled: There's Still Tomorrow
129: Got Details For Movie Titled: Jujutsu Kaisen 0
130: Got Details For Movie Titled: Full Metal Jacket
131: Got Details For Movie Titled: Terminator 2: Judgment Day
132: Got Details For Movie Titled: Wonder
133: Got Details For Movie Titled: Stalker
134: Got Details For Movie Titled: Reservoir Dogs
135: Got Details For Movie Titled: Zack Snyder's Justice League
136: Got Details For Movie Titled: Call Me by Your Name
137: Got Details For Movie Titled: Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb
138: Got Details For Movie Titled: Wild Strawberries
139: Got Details For Movie Titled: Lock, Stock and Two Smoking Barrels
140: Got Details For Movie Titled: Senna
141: Got Details For Movie Titled: The Father
142: Got Details For Movie Titled: Portrait of a Lady on Fire
143: Got Details For Movie Titled: Soul
144: Got Details For Movie Titled: Double Indemnity
145: Got Details For Movie Titled: Metropolis
146: Got Details For Movie Titled: Palmer
147: Got Details For Movie Titled: In the Mood for Love
148: Got Details For Movie Titled: Mortal Kombat Legends: Scorpion's Revenge
149: Got Details For Movie Titled: The Hate U Give
150: Got Details For Movie Titled: The Invisible Guest
151: Got Details For Movie Titled: Prisoners
152: Got Details For Movie Titled: Yojimbo
153: Got Details For Movie Titled: WALL·E
154: Got Details For Movie Titled: Some Like It Hot
155: Got Details For Movie Titled: Incendies
156: Got Details For Movie Titled: Transformers One
157: Got Details For Movie Titled: The Hunt
158: Got Details For Movie Titled: Paris, Texas
159: Got Details For Movie Titled: Purple Hearts
160: Got Details For Movie Titled: Eternal Sunshine of the Spotless Mind
161: Got Details For Movie Titled: The Tale of The Princess Kaguya
162: Got Details For Movie Titled: La Haine
163: Got Details For Movie Titled: Harry Potter and the Deathly Hallows: Part 2
164: Got Details For Movie Titled: Miraculous World: New York, United HeroeZ
165: Got Details For Movie Titled: Das Boot
166: Got Details For Movie Titled: All About Eve
167: Got Details For Movie Titled: M
168: Got Details For Movie Titled: Along with the Gods: The Two Worlds
169: Got Details For Movie Titled: There Will Be Blood
170: Got Details For Movie Titled: My Neighbor Totoro
171: Got Details For Movie Titled: La Dolce Vita
172: Got Details For Movie Titled: Rashomon
173: Got Details For Movie Titled: The Thing
174: Got Details For Movie Titled: Three Billboards Outside Ebbing, Missouri
175: Got Details For Movie Titled: Pride & Prejudice
176: Got Details For Movie Titled: 2001: A Space Odyssey
177: Got Details For Movie Titled: A Taxi Driver
178: Got Details For Movie Titled: Sherlock Jr.
179: Got Details For Movie Titled: Guillermo del Toro's Pinocchio
180: Got Details For Movie Titled: Oppenheimer
181: Got Details For Movie Titled: Memories of Murder
182: Got Details For Movie Titled: A Dog's Journey
183: Got Details For Movie Titled: Ran
184: Got Details For Movie Titled: Elite Squad
185: Got Details For Movie Titled: Hidden Figures
186: Got Details For Movie Titled: The Elephant Man
187: Got Details For Movie Titled: Lion
188: Got Details For Movie Titled: The Grand Budapest Hotel
189: Got Details For Movie Titled: My Name Is Khan
190: Got Details For Movie Titled: The Lives of Others
191: Got Details For Movie Titled: On My Skin
192: Got Details For Movie Titled: The Wolf of Wall Street
193: Got Details For Movie Titled: The Sting
194: Got Details For Movie Titled: Flipped
195: Got Details For Movie Titled: Amadeus
196: Got Details For Movie Titled: The 400 Blows
197: Got Details For Movie Titled: How to Train Your Dragon: Homecoming
198: Got Details For Movie Titled: Dial M for Murder
199: Got Details For Movie Titled: For a Few Dollars More
200: Got Details For Movie Titled: Requiem for a Dream
201: Got Details For Movie Titled: Hilda and the Mountain King
202: Got Details For Movie Titled: Monster High: Frights, Camera, Action!
203: Got Details For Movie Titled: Vengeance Is Mine
204: Got Details For Movie Titled: My Dinner with Andre
205: Got Details For Movie Titled: Mind Game
206: Got Details For Movie Titled: The Taste of Tea
207: Got Details For Movie Titled: Zorba the Greek
208: Got Details For Movie Titled: No Man's Land
209: Got Details For Movie Titled: Au Revoir les Enfants
210: Got Details For Movie Titled: The Music Room
211: Got Details For Movie Titled: Almost Famous
212: Got Details For Movie Titled: Elvis
213: Got Details For Movie Titled: BlacKkKlansman
214: Got Details For Movie Titled: A Star Is Born
215: Got Details For Movie Titled: Messi
216: Got Details For Movie Titled: The Skin I Live In
217: Got Details For Movie Titled: Hercules
218: Got Details For Movie Titled: Band of Outsiders
219: Got Details For Movie Titled: Hero
220: Got Details For Movie Titled: The King of Laughter
221: Got Details For Movie Titled: I Can Only Imagine
222: Got Details For Movie Titled: The Insult
223: Got Details For Movie Titled: Unknown Soldier
224: Got Details For Movie Titled: The Shack
225: Got Details For Movie Titled: Carol
226: Got Details For Movie Titled: Spellbound
227: Got Details For Movie Titled: Boyhood
228: Got Details For Movie Titled: Suspiria
229: Got Details For Movie Titled: How to Steal a Million
230: Got Details For Movie Titled: Cuba and the Cameraman
231: Got Details For Movie Titled: The Secret Life of Bees
232: Got Details For Movie Titled: The Jester
233: Got Details For Movie Titled: Tad, the Lost Explorer and the Emerald Tablet
234: Got Details For Movie Titled: Upgrade
235: Got Details For Movie Titled: Balloon
236: Got Details For Movie Titled: To Sir, with Love
237: Got Details For Movie Titled: In the Shadow of the Moon
238: Got Details For Movie Titled: After Hours
239: Got Details For Movie Titled: The Name of the Rose
240: Got Details For Movie Titled: Rescued by Ruby
241: Got Details For Movie Titled: ¿Y Cómo Es Él?
242: Got Details For Movie Titled: Rogue One: A Star Wars Story
243: Got Details For Movie Titled: Caliber 9
244: Got Details For Movie Titled: The 36th Chamber of Shaolin
245: Got Details For Movie Titled: My Cousin Vinny
246: Got Details For Movie Titled: The Quiet Girl
247: Got Details For Movie Titled: Mars Express
248: Got Details For Movie Titled: All Three of Us
249: Got Details For Movie Titled: The French Connection
250: Got Details For Movie Titled: Ghostbusters
251: Got Details For Movie Titled: Sweet Family
252: Got Details For Movie Titled: The Book Thief
253: Got Details For Movie Titled: Puella Magi Madoka Magica the Movie Part I: Beginnings
254: Got Details For Movie Titled: The Devils
255: Got Details For Movie Titled: The First Day of the Rest of Your Life
256: Got Details For Movie Titled: The Rules of the Game
257: Got Details For Movie Titled: Bonnie and Clyde
258: Got Details For Movie Titled: Listen to Me Marlon
259: Got Details For Movie Titled: Life Itself
260: Got Details For Movie Titled: The Mattei Affair
261: Got Details For Movie Titled: Father and Daughter
262: Got Details For Movie Titled: Oliver Twist
263: Got Details For Movie Titled: In Bruges
264: Got Details For Movie Titled: Ludwig
265: Got Details For Movie Titled: Dawn of the Dead
266: Got Details For Movie Titled: About Fate
267: Got Details For Movie Titled: I Lost My Body
268: Got Details For Movie Titled: Deadpool 2
269: Got Details For Movie Titled: Play It Again, Sam
270: Got Details For Movie Titled: There Is No Evil
271: Got Details For Movie Titled: mid90s
272: Got Details For Movie Titled: anohana: The Flower We Saw That Day - The Movie
273: Got Details For Movie Titled: All That Jazz
274: Got Details For Movie Titled: First Blood
275: Got Details For Movie Titled: Dad Wanted
276: Got Details For Movie Titled: The Suicide Squad
277: Got Details For Movie Titled: Camera Buff
278: Got Details For Movie Titled: The Thin Man
279: Got Details For Movie Titled: The Double Life of Véronique
280: Got Details For Movie Titled: Ed Wood
281: Got Details For Movie Titled: Death Whisperer
282: Got Details For Movie Titled: Night Is Short, Walk On Girl
283: Got Details For Movie Titled: Fate/stay night: Heaven's Feel I. Presage Flower
284: Got Details For Movie Titled: One Piece Film: Z
285: Got Details For Movie Titled: The Man Who Copied
286: Got Details For Movie Titled: Days of Wine and Roses
287: Got Details For Movie Titled: The Official Story
288: Got Details For Movie Titled: Scott Pilgrim vs. the World
289: Got Details For Movie Titled: Fear City: A Family-Style Comedy
290: Got Details For Movie Titled: Batman: Mask of the Phantasm
291: Got Details For Movie Titled: Patton
292: Got Details For Movie Titled: The Invisible Man
293: Got Details For Movie Titled: Three Wishes for Cinderella
294: Got Details For Movie Titled: The Wave
295: Got Details For Movie Titled: Eyes Wide Shut
296: Got Details For Movie Titled: Clara
297: Got Details For Movie Titled: Love Everlasting
298: Got Details For Movie Titled: The Little Matchgirl
299: Got Details For Movie Titled: How the Grinch Stole Christmas!
300: Got Details For Movie Titled: The Bridge
301: Got Details For Movie Titled: The Cursed: Dead Man's Prey
302: Got Details For Movie Titled: The Two Popes
303: Got Details For Movie Titled: Night and the City
304: Got Details For Movie Titled: Men of Honor
305: Got Details For Movie Titled: Back to the Future Part III
306: Got Details For Movie Titled: Furiosa: A Mad Max Saga
307: Got Details For Movie Titled: Balkan Line
308: Got Details For Movie Titled: I, Tonya
309: Got Details For Movie Titled: Still Alice
310: Got Details For Movie Titled: The Roaring Twenties
311: Got Details For Movie Titled: Fist of Legend
312: Got Details For Movie Titled: Breaking the Waves
313: Got Details For Movie Titled: For the Love of Spock
314: Got Details For Movie Titled: Gamera: Guardian of the Universe
315: Got Details For Movie Titled: Winnie-the-Pooh and a Busy Day
316: Got Details For Movie Titled: You Can't Take It with You
317: Got Details For Movie Titled: The Asphalt Jungle
318: Got Details For Movie Titled: The Age of Adaline
319: Got Details For Movie Titled: The Life and Death of Colonel Blimp
320: Got Details For Movie Titled: In Cold Blood
321: Got Details For Movie Titled: Willy Wonka & the Chocolate Factory
322: Got Details For Movie Titled: Lucky Number Slevin
323: Got Details For Movie Titled: Free Guy
324: Got Details For Movie Titled: Die Nibelungen: Kriemhild's Revenge
325: Got Details For Movie Titled: A Grand Day Out
326: Got Details For Movie Titled: Blue Bayou
327: Got Details For Movie Titled: RBG
328: Got Details For Movie Titled: Lupin the Third: Jigen's Gravestone
329: Got Details For Movie Titled: Bootleggers
330: Got Details For Movie Titled: Gaslight
331: Got Details For Movie Titled: Midnight Express
332: Got Details For Movie Titled: The Taking of Pelham One Two Three
333: Got Details For Movie Titled: Reservoir Dogs
334: Got Details For Movie Titled: I've Always Liked You
335: Got Details For Movie Titled: For the Birds
336: Got Details For Movie Titled: A Perfect World
337: Got Details For Movie Titled: Badlands
338: Got Details For Movie Titled: Jane
339: Got Details For Movie Titled: Taipei Story
340: Got Details For Movie Titled: 12.12: The Day
341: Got Details For Movie Titled: The Irishman: In Conversation
342: Got Details For Movie Titled: Mr & Mme Adelman
343: Got Details For Movie Titled: Aquarius
344: Got Details For Movie Titled: Toy Story 4
345: Got Details For Movie Titled: The White Ribbon
346: Got Details For Movie Titled: The Son
347: Got Details For Movie Titled: This Is England
348: Got Details For Movie Titled: One, Two, Three
349: Got Details For Movie Titled: Robot Chicken: Star Wars Episode II
350: Got Details For Movie Titled: The Discreet Charm of the Bourgeoisie
351: Got Details For Movie Titled: Letters from Iwo Jima
352: Got Details For Movie Titled: Güeros
353: Got Details For Movie Titled: High School of the Dead: Drifters of the Dead
354: Got Details For Movie Titled: The Fantastic Flying Books of Mr. Morris Lessmore
355: Got Details For Movie Titled: Running on Empty
356: Got Details For Movie Titled: Kes
357: Got Details For Movie Titled: Glory
358: Got Details For Movie Titled: The Man Who Would Be King
359: Got Details For Movie Titled: Five Nights at Freddy's
360: Got Details For Movie Titled: Waterloo Bridge
361: Got Details For Movie Titled: Son of the Bride
362: Got Details For Movie Titled: Welcome to Dongmakgol
363: Got Details For Movie Titled: The Power of One
364: Got Details For Movie Titled: The Road Home
365: Got Details For Movie Titled: A Bittersweet Life
366: Got Details For Movie Titled: Samsara
367: Got Details For Movie Titled: The Most Beautiful Girl in the World
368: Got Details For Movie Titled: Once Upon a Time in Anatolia
369: Got Details For Movie Titled: The Green Ray
370: Got Details For Movie Titled: Floating Weeds
371: Got Details For Movie Titled: Barbie as The Princess & the Pauper
372: Got Details For Movie Titled: Volver
373: Got Details For Movie Titled: A Quiet Place Part II
374: Got Details For Movie Titled: Dexter's Laboratory: Ego Trip
375: Got Details For Movie Titled: Thesis
376: Got Details For Movie Titled: Aguirre, the Wrath of God
377: Got Details For Movie Titled: Pandora's Box
378: Got Details For Movie Titled: Baki Hanma VS Kengan Ashura

## Put Data into a Viewable Dataframe

In [21]:
import pandas as pd

### Movies Dataframe

In [24]:
movies_df = pd.DataFrame(all_movies)

In [26]:
movies_df.columns

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'release_date', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [28]:
movies_df = movies_df.drop(['backdrop_path', 'genre_ids', 'poster_path', 'original_title', 'video'], axis = 1)

In [30]:
movies_df.head()

,adult,id,original_language,overview,popularity,release_date,title,vote_average,vote_count
0,False,278,en,Imprisoned in the 1940s for the double murder ...,34.6551,1994-09-23,The Shawshank Redemption,8.710,28243
1,False,238,en,"Spanning the years 1945 to 1955, a chronicle o...",50.6029,1972-03-14,The Godfather,8.686,21408
2,False,240,en,In the continuing saga of the Corleone crime f...,16.7806,1974-12-20,The Godfather Part II,8.571,12930
3,False,424,en,The true story of how businessman Oskar Schind...,24.8390,1993-12-15,Schindler's List,8.565,16409
4,False,389,en,The defense and the prosecution have rested an...,23.7899,1957-04-10,12 Angry Men,8.548,9109

### Movie Details Dataframe

In [91]:
details_df = pd.DataFrame(detailed_data)

In [93]:
details_df.columns

Index(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres',
       'homepage', 'id', 'imdb_id', 'origin_country', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'video', 'vote_average', 'vote_count'],
      dtype='object')

In [95]:
details_df['num_spoken_languages'] = details_df['spoken_languages'].apply(lambda x: len(x) if isinstance(x, list) else None)

In [97]:
details_df['belongs_to_collection_boolean'] = details_df['belongs_to_collection'].apply(lambda x: False if x == None else True)

In [99]:
details_df['genres']= details_df['genres'].apply(lambda x: [genre['name'] for genre in x] if isinstance(x, list) else [])

In [101]:
details_df['production_companies'] = details_df['production_companies'].apply(lambda x: [company_name['name'] for company_name in x] if isinstance(x, list) else [])

In [103]:
details_df = details_df[['belongs_to_collection_boolean', 'budget', 'genres', 'id', 'origin_country', 'production_companies', 'revenue', 'runtime', 'num_spoken_languages']]

In [105]:
details_df.head()

,belongs_to_collection_boolean,budget,genres,id,origin_country,production_companies,revenue,runtime,num_spoken_languages
0,False,25000000,"[Drama, Crime]",278,[US],[Castle Rock Entertainment],28341469,142,1
1,True,6000000,"[Drama, Crime]",238,[US],"[Paramount Pictures, Alfran Productions]",245066411,175,3
2,True,13000000,"[Drama, Crime]",240,[US],"[Paramount Pictures, The Coppola Company, Amer...",102600000,202,4
3,False,22000000,"[Drama, History, War]",424,[US],[Amblin Entertainment],321365567,195,4
4,False,397751,[Drama],389,[US],"[United Artists, Orion-Nova Productions]",4360000,97,1

### Merge Dataframes and Resolve Any Duplicates

In [108]:
full_movie_list = pd.merge(movies_df, details_df, on='id', how='left')

In [110]:
full_movie_list

,adult,id,original_language,overview,popularity,release_date,title,vote_average,vote_count,belongs_to_collection_boolean,budget,genres,origin_country,production_companies,revenue,runtime,num_spoken_languages
0,False,278,en,Imprisoned in the 1940s for the double murder ...,34.6551,1994-09-23,The Shawshank Redemption,8.710,28243,False,25000000,"[Drama, Crime]",[US],[Castle Rock Entertainment],28341469,142,1
1,False,278,en,Imprisoned in the 1940s for the double murder ...,34.6551,1994-09-23,The Shawshank Redemption,8.710,28243,False,25000000,"[Drama, Crime]",[US],[Castle Rock Entertainment],28341469,142,1
2,False,238,en,"Spanning the years 1945 to 1955, a chronicle o...",50.6029,1972-03-14,The Godfather,8.686,21408,True,6000000,"[Drama, Crime]",[US],"[Paramount Pictures, Alfran Productions]",245066411,175,3
3,False,238,en,"Spanning the years 1945 to 1955, a chronicle o...",50.6029,1972-03-14,The Godfather,8.686,21408,True,6000000,"[Drama, Crime]",[US],"[Paramount Pictures, Alfran Productions]",245066411,175,3
4,False,240,en,In the continuing saga of the Corleone crime f...,16.7806,1974-12-20,The Godfather Part II,8.571,12930,True,13000000,"[Drama, Crime]",[US],"[Paramount Pictures, The Coppola Company, Amer...",102600000,202,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087,False,267557,it,,0.2815,2014-04-30,Un fidanzato per mia moglie,5.000,110,False,0,[Comedy],[IT],"[IBC MOvie, RAI]",0,97,1
1088,False,242088,en,Years after their successful restaurant review...,0.2821,2014-04-24,The Trip to Italy,6.325,243,True,0,"[Comedy, Drama]",[GB],"[Revolution Films, Baby Cow Productions, BBC F...",0,108,2
1089,False,43648,it,A poster worker must remove the poster of the ...,0.2821,1991-12-20,The Comics 2,5.700,217,True,0,[Comedy],[IT],"[Maura International Films, Penta Film, Cecchi...",0,87,1
1090,False,13296,tr,Failed magician Iskender decides to do a tour ...,0.2822,2006-10-20,The Magician,6.900,159,False,0,"[Comedy, Drama]",[TR],[BKM Film],0,122,1
1091,False,56972,it,Two different men living in Milan lose their j...,0.2837,2007-02-09,Mi fido di te,6.600,193,False,0,[Comedy],[IT],[],0,100,1

In [112]:
full_movie_list['id'].duplicated().sum()

138

In [114]:
full_movie_list = full_movie_list.drop_duplicates(subset = 'id')

In [116]:
full_movie_list['id'].duplicated().sum()

0

In [120]:
full_movie_list.to_csv("Movies.csv")